name: Unit tests

on:
  # For manual exec
  # (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch: {}
  push:
    branches:
      - ci-workflow

env: {}

jobs:
  integration-test:
    name: BEE Unit Tests
    # Note: Needs to run on 22.04 or later since slurmrestd doesn't seem to be
    # available on 20.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Dependency Install
        run: ./ci/deps_install.sh
      - name: Slurm Setup and Install
        run: ./ci/slurm_start.sh
      - name: BEE Install
        run: ./ci/bee_install.sh
      # TODO: Add the script for the unit tests here
      - name: Unit tests
        run: |
          #!/bin/sh
          . ./venv/bin/activate
          pytest src/beeflow/tests/test_*.py
